### ISSUE TITLE
MapeiaMA - Paraibano

### ISSUE THREAD

**Issue by Gustavo22Soaresh** [OSMBrasil/hotosm-tasking-manager#6]
## Descrição curta
Estaremos mapeando edifícios e estradas, recursos hídricos e escolas da cidade de [Paraibano](https://www.openstreetmap.org/relation/332927)

## Descrição

Estaremos mapeando edifícios e estradas, recursos hídricos e escolas da cidade de [Paraibano](https://www.openstreetmap.org/relation/332927)

## Link para geometria da área do projeto

https://raw.githubusercontent.com/mapeia/MapeiaMA/main/Limites%20das%20Cidades/Paraibano.geojson

## Elementos a serem mapeados

- [x] Ruas/estradas
- [x] Edificações
- [x] Rios e lagos
- [ ] Uso do solo
- [ ] Outros

## Imagem aérea recomendada
Maxar Premium

## Instruções de mapeamento
Instruções para mapear edifícios

Paraibano NÃO está bem mapeado no OSM, portanto, tente ser o mais completo possível ao adicionar novos recursos ao mapa!

Depois de alinhar as imagens aos recursos existentes, comece a mapear primeiro todos os edifícios não mapeados. Para identificar edifícios já mapeados, dê um zoom em sua tarefa e examine cuidadosamente o conteúdo existente. Tente não redesenhar os edifícios já existentes!

Após desenhar o contorno, use o botão 'Q' no editor iD para ortogonalizar os cantos. Se houver algum edifício circular, use o botão 'O' para criar uma estrutura circular.

Muitos edifícios são muito próximos, mas na verdade não se tocam. Tente mapeá-los o mais próximo possível, sem permitir que eles se conectem ou compartilhem nós entre si ou com as ruas. No editor iD, pressionar o botão "Alt" impedirá que os nós "se juntem" e se conectem acidentalmente.

No editor iD, quando você mapear uma construção, procure em "Selecione o tipo de elemento" a categoria "Edifício", que deverá aparecer no topo da lista, e, posteriormente, selecione a etiqueta "Edifício". Essa é a tag de construção mais genérica que podemos usar, pois quase nunca podemos distinguir o uso mais específico de qualquer construção apenas a partir de imagens. Se você tiver certeza de informações adicionais sobre o edifício que você mapeou (igreja, café, loja etc.), adicione-as aqui! Por favor, não adicione aqui informações específicas, como endereço, número de residentes, nomes, etc.

Instruções para mapear e marcar as estradas

A maioria das estradas principais (tipo rodovia e via expressa) na área estão mapeadas. Concentre-se nas estradas residenciais e de serviço, bem como nos caminhos, acessíveis apenas a pé. Tente mapear um pouco além do quadrado da tarefa, para que a pessoa que mapear o quadrado da tarefa ao lado do seu possa conectá-los facilmente. Sempre conecte estradas a outras estradas onde elas se encontram e nunca termine estradas nas bordas dos polígonos da área residencial.

Use as seguintes tags para mapear estradas no iD Feature Editor:

Rua residencial: selecione a etiqueta "residencial" ou "residential" para estradas que são principalmente para acesso à moradia.

Auto-estrada: selecione a etiqueta "auto-estrada" ou ''motorway" - rodovias de alta capacidade projetadas para transportar com segurança um tráfego motorizado rápido.

Ruas de serviço: selecione a etiqueta "service" - ruas dentro de mercados, shoppings, escritórios / estações de serviço, etc.

Rua residencial: selecione a etiqueta "living street" - ruas estreitas principalmente para acesso às residências

Caminho para pedestre: selecione a tag "footway" - caminhos acessíveis apenas a pé

## Nível de dificuldade de mapeamento

- [ ] Fácil
- [x] Intermediário
- [ ] Avançado

## Usuários responsáveis pela validação
 - [PlayzinhoAgro](https://www.openstreetmap.org/user/PlayzinhoAgro)

## Outras informações
Changset:
#MapeiaMA Paraibano, Mapeamento de estradas, edifícios e corpos d'agua

**Comment by vgeorge** [comment]
O projeto foi criado: https://tasks.hotosm.org/projects/10980

@Playzinho confira se está ok, por favor. Eu removi "escolas" do título e descrição, não há instruções sobre como identificar este tipo de feição e imaginei que não como fazer isso apenas com imagens de satélite. Também não há instruções para cursos d'água, você poderia mandar aqui pra gente adicionar? Ou podemos tirar da descrição, se preferir.

Eu criei uma planilha no Google Sheets para facilitar a geração dos metadados dos projetos:

https://docs.google.com/spreadsheets/d/1Wt9M45JZw-aL_NR7jaDDn11JT1ITwQnKS4nwQQS6Nxc/edit?usp=sharing

A idéia é entrar apenas com os dados básicos do projeto e depois copiar e colar para Tasking Manager.

@Playzinho @willemarcel para os próximos projetos vamos tentar usar esta planilha, duplicando a última folha criada.

**Comment by Gustavo22Soaresh** [comment]
obrigado, pode ser sim removido, a tarefa das escolas são postadas no Maproullete https://maproulette.org/browse/challenges/18757 é usado o dados no INEPDATA e conferido com os dados existentes do OSM. Sobre instruções de hidrografia vou ficar devendo já que essas instruções foram copiadas de outro projeto do TM

**Comment by matheusgomesms** [comment]
Projeto validado, favor fechar issue @Playzinho @vgeorge
