### ISSUE TITLE
Adição de vias em Guaramiranga-CE

### ISSUE THREAD

**Issue by matheusgomesms** [OSMBrasil/hotosm-tasking-manager#7]
## Descrição curta

Mapeamento de estradas no município de [Guaramiranga (CE)](https://www.openstreetmap.org/relation/302474).

## Descrição

Estaremos mapeando estradas no município de Guaramiranga (CE). O projeto como um todo pode ser visto na [Wiki](https://wiki.openstreetmap.org/wiki/Cear%C3%A1/Projetos/Adi%C3%A7%C3%A3o_de_vias).

## Link para geometria da área do projeto
https://raw.githubusercontent.com/matheusgomesms/osm-ce/main/files/limits/Guaramiranga.geojson

## Elementos a serem mapeados

- [x] Ruas/estradas
- [ ] Edificações
- [ ] Rios e lagos
- [ ] Uso do solo
- [ ] Outros

## Imagem aérea recomendada

Maxar Premium

### Instruções detalhadas
Veja vídeos detalhados sobre o projeto [aqui](https://wiki.openstreetmap.org/wiki/Cear%C3%A1/Projetos/Adi%C3%A7%C3%A3o_de_vias#Instru%C3%A7%C3%B5es).

### Como adicionar a camada de ruas do IBGE

No editor iD, vá ao menu do lado direito e clique em Configurações de Fundo (ou aperte a tecla B). Desça até o submenu **Sobreposições** e selecione a última opção **IBGE Nomes de Ruas**.

### Instruções para mapear e marcar as estradas

A maioria das estradas principais (tipo rodovia e via expressa) na área estão mapeadas. Concentre-se nas estradas residenciais e de serviço, bem como nos caminhos, acessíveis apenas a pé. Tente mapear um pouco além do quadrado da tarefa, para que a pessoa que mapear o quadrado da tarefa ao lado do seu possa conectá-los facilmente. Sempre conecte estradas a outras estradas onde elas se encontram e nunca termine estradas nas bordas dos polígonos da área residencial.

Use as seguintes opções para mapear estradas no editor iD:

- **Rua residencial**: selecione a opção ""Via residencial"" para estradas que são principalmente para acesso à moradia.
- **Auto-estrada**: selecione a opção ""Via troncal"" ou ''Autoestrada"" para rodovias de alta capacidade projetadas para transportar com segurança um tráfego motorizado rápido.
- **Ruas de serviço**: selecione a opção ""Via de Serviço"" para ruas no interior de áreas de mercados, shoppings, escritórios / estações de serviço, etc.
- **Ruas estreitas**: selecione a opção ""Via compartilhada"" - ruas estreitas principalmente para acesso às residências
- **Caminhos de pedestre**: selecione esta opção para caminhos acessíveis apenas a pé

## Nível de dificuldade de mapeamento

- [x] Fácil
- [ ] Intermediário
- [ ] Avançado

## Usuários responsáveis pela validação

[matheusgomesms](https://www.openstreetmap.org/user/matheusgomesms/)

## Outras informações

Comentário do changeset:
#hotosm-project-11084 #ProjetoCeara Adição de vias em Guaramiranga, Ceará

**Comment by matheusgomesms** [comment]
Adicionei o projeto lá no TM: https://tasks.hotosm.org/projects/11084/tasks/

Vou melhorar depois as instruções de mapeamento (inclusive creio que vou fazer um vídeo), pois quero sugerir o RapiD como editor padrão. Assim que tiver isso pronto, atualizo aqui e lá no TM.

**Comment by matheusgomesms** [comment]
Instruções atualizadas, já está em andamento o projeto.

**Comment by matheusgomesms** [comment]
Projeto finalizado, creio que pode ser encerrado.

**Comment by vgeorge** [comment]
Muito bom, @matheusgomesms, obrigado!
